apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-approver
  namespace: openshift-cluster-machine-approver
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
