apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:machine-approver
roleRef:
  kind: ClusterRole
  name: system:openshift:controller:machine-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-machine-approver
  name: machine-approver-sa
