apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-cluster-machine-approver
  name: origin-cluster-machine-approver-config
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
    authentication:
      disabled: true
    authorization:
      disabled: true