apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-approver
  namespace: openshift-cluster-machine-approver
roleRef:
  kind: Role
  name: machine-approver
  namespace: openshift-cluster-machine-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-machine-approver
  name: machine-approver-sa
